### ISSUE TITLE
Fix `db` and `schema` path in order to generate migration

### ISSUE THREAD

**Issue by shivam-sharma7** [profilecity/vidur#122]
While `docker compose --profile dev up --build` set up vidur with latest changes I got the following error

```powershell
PS C:\Users\shivam sharma\Desktop\My Project\open-source\vidur> docker compose --profile dev up --build        
[+] Building 324.6s (11/11) FINISHED                                                              docker:desktop-linux 
 => [app internal] load build definition from Dockerfile                                                          0.0s 
 => => transferring dockerfile: 334B                                                                              0.0s 
 => [app internal] load metadata for docker.io/library/node:22.8-alpine                                           3.3s 
 => [app auth] library/node:pull token for registry-1.docker.io                                                   0.0s 
 => [app internal] load .dockerignore                                                                             0.0s 
 => => transferring context: 273B                                                                                 0.0s 
 => [app stage-0 1/4] FROM docker.io/library/node:22.8-alpine@sha256:008735b83ef98c7635b5b73cb9b597172fe1895619a  0.0s 
 => [app internal] load build context                                                                             0.1s 
 => => transferring context: 344.82kB                                                                             0.1s 
 => CACHED [app stage-0 2/4] WORKDIR /app                                                                         0.0s 
 => [app stage-0 3/4] COPY package.json yarn.lock ./                                                              0.1s 
 => [app stage-0 4/4] RUN --mount=type=cache,target=/root/.cache/yarn     yarn install                          296.9s 
 => [app] exporting to image                                                                                     23.9s 
 => => exporting layers                                                                                          23.9s 
 => => writing image sha256:673985176713f697dde27f73777b598614c5c92dfda3872888e360263c4d10c2                      0.0s
 => => naming to docker.io/library/vidur-app                                                                      0.0s
 => [app] resolving provenance for metadata file                                                                  0.0s
[+] Running 2/2
 ✔ Container database   Created                                                                                   0.0s 
 ✔ Container vidur_app  Recreated                                                                                 0.2s 
Attaching to database, vidur_app
database   |
database   | PostgreSQL Database directory appears to contain a database; Skipping initialization
database   | 
database   | 2024-09-06 09:27:29.892 UTC [1] LOG:  starting PostgreSQL 15.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
database   | 2024-09-06 09:27:29.892 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database   | 2024-09-06 09:27:29.892 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database   | 2024-09-06 09:27:29.899 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"        
database   | 2024-09-06 09:27:29.910 UTC [24] LOG:  database system was shut down at 2024-09-06 01:18:05 UTC
database   | 2024-09-06 09:27:29.931 UTC [1] LOG:  database system is ready to accept connections                      
vidur_app  | yarn install v1.22.22
vidur_app  | [1/4] Resolving packages...
vidur_app  | [2/4] Fetching packages...
vidur_app  | warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
vidur_app  | [3/4] Linking dependencies...
vidur_app  | warning " > @tailwindcss/forms@0.5.8" has unmet peer dependency "tailwindcss@>=3.0.0 || >= 3.0.0-alpha.1 || >= 4.0.0-alpha.20".                                                                                                  
vidur_app  | warning "nuxt > @nuxt/devtools@1.4.1" has unmet peer dependency "vite@*".
vidur_app  | warning "nuxt > @nuxt/devtools > @nuxt/devtools-kit@1.4.1" has unmet peer dependency "vite@*".            
vidur_app  | warning "nuxt > @nuxt/devtools > vite-plugin-inspect@0.8.7" has unmet peer dependency "vite@^3.1.0 || ^4.0.0 || ^5.0.0-0".                                                                                                       
vidur_app  | warning "nuxt > @nuxt/devtools > vite-plugin-vue-inspector@5.1.3" has unmet peer dependency "vite@^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0".                                                                                             
vidur_app  | warning "nuxt > @nuxt/devtools > @vue/devtools-core > vite-hot-client@0.2.3" has unmet peer dependency "vite@^2.6.0 || ^3.0.0 || ^4.0.0 || ^5.0.0-0".                                                                            
vidur_app  | warning "nuxt-icon > @nuxt/devtools-kit@1.3.9" has unmet peer dependency "vite@*".
vidur_app  | [4/4] Building fresh packages...                                                                          
vidur_app  | $ nuxt prepare
vidur_app  | [nuxt:tailwindcss] ℹ Using default Tailwind CSS file
vidur_app  | ℹ Using zod with vee-validate
vidur_app  | ℹ Running with compatibility version 4
vidur_app  | ✔ Types generated in .nuxt
vidur_app  | $ husky
vidur_app  | git command not foundDone in 24.09s.
vidur_app  | yarn run v1.22.22
vidur_app  | $ drizzle-kit migrate
vidur_app  | No config path provided, using default 'drizzle.config.ts'
vidur_app  | Reading config file '/app/drizzle.config.ts'
vidur_app  | Using 'pg' driver for database querying
vidur_app  | Error: Can't find meta/_journal.json file
vidur_app  |     at readMigrationFiles (/app/node_modules/src/migrator.ts:41:9)
vidur_app  |     at migrate (/app/node_modules/src/node-postgres/migrator.ts:9:21)                                     
vidur_app  |     at migrateFn (/app/node_modules/drizzle-kit/bin.cjs:71877:18)                                         
vidur_app  |     at Object.handler (/app/node_modules/drizzle-kit/bin.cjs:83571:11)
vidur_app  |     at async run (/app/node_modules/drizzle-kit/bin.cjs:82064:7)
vidur_app  | error Command failed with exit code 1.                                                                    
vidur_app  | [⣷] applying migrations...info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                                                                                   
vidur_app exited with code 1
```

**Comment by shivam-sharma7** [comment]
We can see it fail while applying migrations

**Comment by amandesai01** [comment]
That is coming from recent Nuxt4 restructure. Go ahead with a PR if you can. All you need to do is update the path.
