### ISSUE TITLE
Docker dev environment doesn't work

### ISSUE THREAD

**Issue by amandesai01** [profilecity/vidur#97]
In current scenario, when I run the command provided, it shows unable to connect. Reason I suspect is, vidur app starts before database can start accepting connection. Below are the logs.

```
vidur_app  | yarn run v1.22.22
vidur_app  | $ drizzle-kit migrate
vidur_app  | No config path provided, using default 'drizzle.config.ts'
vidur_app  | Reading config file '/app/drizzle.config.ts'
database   | ok
database   | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
database   | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
database   | ok
database   | 
database   | 
database   | Success. You can now start the database server using:
database   | 
database   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
database   | 
vidur_app  | Using 'pg' driver for database querying
database   | waiting for server to start....2024-08-23 13:59:33.828 UTC [36] LOG:  starting PostgreSQL 15.1 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
database   | 2024-08-23 13:59:33.830 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database   | 2024-08-23 13:59:33.845 UTC [39] LOG:  database system was shut down at 2024-08-23 13:59:33 UTC
database   | 2024-08-23 13:59:33.853 UTC [36] LOG:  database system is ready to accept connections
database   |  done
database   | server started
vidur_app  | [⣷] applying migrations...Error: connect ECONNREFUSED 172.28.0.2:5432
vidur_app  |     at /app/node_modules/pg-pool/index.js:45:11
vidur_app  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
vidur_app  |     at async PgDialect.migrate (/app/node_modules/src/pg-core/dialect.ts:72:3)
vidur_app  |     at async migrate (/app/node_modules/src/node-postgres/migrator.ts:10:2) {
vidur_app  |   errno: -111,
vidur_app  |   code: 'ECONNREFUSED',
vidur_app  |   syscall: 'connect',
vidur_app  |   address: '172.28.0.2',
vidur_app  |   port: 5432
vidur_app  | }
database   | CREATE DATABASE
database   | 
database   | 
database   | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
database   | 
database   | waiting for server to shut down...2024-08-23 13:59:33.998 UTC [36] LOG:  received fast shutdown request
database   | .2024-08-23 13:59:33.999 UTC [36] LOG:  aborting any active transactions
database   | 2024-08-23 13:59:34.002 UTC [36] LOG:  background worker "logical replication launcher" (PID 42) exited with exit code 1
database   | 2024-08-23 13:59:34.005 UTC [37] LOG:  shutting down
database   | 2024-08-23 13:59:34.005 UTC [37] LOG:  checkpoint starting: shutdown immediate
vidur_app  | error Command failed with exit code 1.
vidur_app  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
database   | 2024-08-23 13:59:34.057 UTC [37] LOG:  checkpoint complete: wrote 918 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.016 s, sync=0.032 s, total=0.053 s; sync files=250, longest=0.018 s, average=0.001 s; distance=4222 kB, estimate=4222 kB
database   | 2024-08-23 13:59:34.070 UTC [36] LOG:  database system is shut down
database   |  done
database   | server stopped
database   | 
database   | PostgreSQL init process complete; ready for start up.
database   | 
database   | 2024-08-23 13:59:34.133 UTC [1] LOG:  starting PostgreSQL 15.1 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
database   | 2024-08-23 13:59:34.133 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database   | 2024-08-23 13:59:34.133 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database   | 2024-08-23 13:59:34.136 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database   | 2024-08-23 13:59:34.142 UTC [52] LOG:  database system was shut down at 2024-08-23 13:59:34 UTC
database   | 2024-08-23 13:59:34.150 UTC [1] LOG:  database system is ready to accept connections
vidur_app exited with code 1
```

**Comment by amandesai01** [comment]
cc: @shivam-sharma7 @akashvarun10

**Comment by amandesai01** [comment]
Confirmed. So once it fails, database is still up. So if I go to docker dashboard and manually turn on vidur, it works, given that db is running.

**Comment by akashvarun10** [comment]
@amandesai01  Even I encountered the `ECONNREFUSED` error, then used `Ctrl+C `to stop the process and re-ran `docker compose up`.

The `ECONNREFUSED` error occurred because the application tried to connect to the PostgreSQL database before it was fully ready, leading to a failed connection

I was expecting the database configuration to be modified to handle retries. However, I can adjust the Dockerfile's CMD instruction to ensure the application waits for the database to be ready.

The `CMD ["sh", "-c", "until nc -z $NUXT_DB_HOST $NUXT_DB_PORT; do echo 'Waiting for the database...'; sleep 5; done && yarn migration:apply && yarn dev"]` command makes the container wait until the database is reachable by checking the connection every 5 seconds, then runs migrations and starts the application.

**Comment by shivam-sharma7** [comment]
@amandesai01 let's see after this PR #101

**Comment by akashvarun10** [comment]
@shivam-sharma7 the DB config file will need to be updated for a permanent fix. Problem is not because we are running via  docker it is because the application tried to connect to the db before it was fully ready, The above is just temporary fix when running via Docker.

**Comment by amandesai01** [comment]
That's a nice fix @akashvarun10! You mind raising a PR? Plus this will only be in dev profile so not at risk.

**Comment by akashvarun10** [comment]
Okay, Sure @amandesai01 .
